.ONESHELL:
SHELL      := $(shell which bash)
.SHELLFLAGS := -ec

VERSION ?=
REF     ?=

.PHONY: vendor-profiles generate-kodex generate-all test-structure plugin-graph plugin-graph-docs docs-serve docs-build release pre-release

vendor-profiles:
	go test ./cmd/vendor-profiles/...
	go run ./cmd/vendor-profiles -manifest scripts/go-vendor-manifest.yml
	$(MAKE) test-structure

generate-kodex:
	go test ./cmd/generate-kodex/...
	go run ./cmd/generate-kodex -manifest scripts/kodex-generate-manifest.yml
	$(MAKE) test-structure

generate-all: vendor-profiles generate-kodex

test-structure:
	bash test/test-plugin-structure.sh
	bash test/test-codex-structure.sh

plugin-graph:
	go test ./cmd/plugin-graph/...
	go run ./cmd/plugin-graph --root klaude-plugin/ validate

# Regenerate the plugin-graph artifacts embedded in the docs site (metrics
# snapshot + full dependency graph). Run automatically before every docs build
# so the published site always reflects the current plugin.
plugin-graph-docs:
	mkdir -p docs/contributing/_generated
	{
	  echo '<!-- Generated by `make plugin-graph-docs` — do not edit by hand. -->'
	  echo
	  echo '```text'
	  go run ./cmd/plugin-graph --root klaude-plugin/ metrics
	  echo '```'
	} > docs/contributing/_generated/plugin-graph-metrics.md
	{
	  echo '<!-- Generated by `make plugin-graph-docs` — do not edit by hand. -->'
	  echo
	  echo '```mermaid'
	  go run ./cmd/plugin-graph --root klaude-plugin/ graph --format mermaid
	  echo '```'
	} > docs/contributing/_generated/plugin-graph-full.md

docs-serve: plugin-graph-docs
	MKDOCS_SITE_URL=http://localhost:8000 mkdocs serve

docs-build: plugin-graph-docs
	MKDOCS_SITE_URL=https://serpro69.github.io/claude-toolbox/ mkdocs build --strict

# https://stackoverflow.com/a/10858332
# Check that given variables are set and all have non-empty values,
# die with an error otherwise.
#
# Params:
#   1. Variable name(s) to test.
#   2. (optional) Error message to print.
check_defined = \
    $(strip $(foreach 1,$1, \
        $(call __check_defined,$1,$(strip $(value 2)))))
__check_defined = \
    $(if $(value $1),, \
      $(error Undefined $1$(if $2, ($2))))

release:
	@:$(call check_defined, VERSION, semantic version string - 'X.Y.Z(-rc.\d+)?')
	# Validate semver format: MAJOR.MINOR.PATCH
	if [[ ! "$(VERSION)" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$$ ]]; then
		echo "Invalid semver format: $(VERSION). Expected format: MAJOR.MINOR.PATCH (e.g., '1.2.3')"
		exit 1
	fi
	gh workflow run release.yml -f version=v$(VERSION)

pre-release:
	@:$(call check_defined, VERSION, semantic version string - 'X.Y.Z(-rc.\d+)?')
	@:$(call check_defined, REF, undefined target branch reference)
	# Validate semver format: MAJOR.MINOR.PATCH with pre-release and optional build metadata
	if [[ ! "$(VERSION)" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$$ ]]; then
		echo "Invalid semver format: $(VERSION). Expected format: MAJOR.MINOR.PATCH-rc.N(\+abc.1)? (e.g., v1.2.3-rc.1 with an optional build identifier)"
		exit 1
	fi
	if [[ "$(REF)" =~ ^master$$ ]]; then
		read -p "Pre-releases should typically NOT be made from $(REF) ref. Do you want to proceed? [y/Y]: " ANSWER && \
		if [ ! "$${ANSWER}" = "y" ] && [ ! "$${ANSWER}" = "Y" ]; then
			exit 1
		fi
	fi
	gh workflow run pre-release.yml -f version=v$(VERSION) -r $(REF)
