.ONESHELL:
.SHELL      := $(shell which bash)
.SHELLFLAGS := -ec

.PHONY: vendor-profiles generate-kodex generate-all test-structure plugin-graph plugin-graph-docs docs-serve docs-build

vendor-profiles:
	go test ./cmd/vendor-profiles/...
	go run ./cmd/vendor-profiles -manifest scripts/go-vendor-manifest.yml
	$(MAKE) test-structure

generate-kodex:
	go test ./cmd/generate-kodex/...
	go run ./cmd/generate-kodex -manifest scripts/kodex-generate-manifest.yml
	$(MAKE) test-structure

generate-all: vendor-profiles generate-kodex

test-structure:
	bash test/test-plugin-structure.sh
	bash test/test-codex-structure.sh

plugin-graph:
	go test ./cmd/plugin-graph/...
	go run ./cmd/plugin-graph --root klaude-plugin/ validate

# Regenerate the plugin-graph artifacts embedded in the docs site (metrics
# snapshot + full dependency graph). Run automatically before every docs build
# so the published site always reflects the current plugin.
plugin-graph-docs:
	mkdir -p docs/contributing/_generated
	{
	  echo '<!-- Generated by `make plugin-graph-docs` — do not edit by hand. -->'
	  echo
	  echo '```text'
	  go run ./cmd/plugin-graph --root klaude-plugin/ metrics
	  echo '```'
	} > docs/contributing/_generated/plugin-graph-metrics.md
	{
	  echo '<!-- Generated by `make plugin-graph-docs` — do not edit by hand. -->'
	  echo
	  echo '```mermaid'
	  go run ./cmd/plugin-graph --root klaude-plugin/ graph --format mermaid
	  echo '```'
	} > docs/contributing/_generated/plugin-graph-full.md

docs-serve: plugin-graph-docs
	MKDOCS_SITE_URL=http://localhost:8000 mkdocs serve

docs-build: plugin-graph-docs
	MKDOCS_SITE_URL=https://serpro69.github.io/claude-toolbox/ mkdocs build --strict
